[versions]
java = "17"
kotlin = "2.2.21"

android-gradle-plugin = "8.13.1"

compose-multiplatform = "1.9.3"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }

jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
